apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolov5-deployment-cloud
  labels:
    app: yolov5-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolov5-cloud
  template:
    metadata:
      labels:
        app: yolov5-cloud
    spec:
      nodeSelector:
        placement: cloud
      containers:
      - name: yolov5
        image: serodioj/iot-project:1.0
        ports:
        - containerPort: 8000
          hostPort: 8000
        env:
        - name: detect_model
          value: "yolov5s"
        - name: placement
          value: "cloud"
